export const CONTACT_ADD_REQUEST = "CONTACT_ADD_REQUEST"
export const CONTACT_ADD_SUCCESS = "CONTACT_ADD_SUCCESS"
export const CONTACT_ADD_FAILURE = "CONTACT_ADD_FAILURE"

export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS"
export const GET_ALL_CONTACTS_FAILURE = "GET_ALL_CONTACTS_FAILURE"

export const CHANGE_CONTACT_PAGE = "CHANGE_CONTACT_PAGE";

export const EDIT_CONTACT_OPEN = "EDIT_CONTACT_OPEN"
export const EDIT_CONTACT_CLOSE = "EDIT_CONTACT_CLOSE"
export const EDIT_CONTACT = "EDIT_CONTACT"