export const ADD_PRODUCT_TO_TRANSACTION_REQUEST = "ADD_PRODUCT_TO_TRANSACTION_REQUEST"
export const ADD_PRODUCT_TO_TRANSACTION_SUCCESS = "ADD_PRODUCT_TO_TRANSACTION_SUCCESS"
export const ADD_PRODUCT_TO_TRANSACTION_FAILURE = "ADD_PRODUCT_TO_TRANSACTION_FAILURE"

export const ADD_EXISTING_PRODUCT_TO_TRANSACTION = "ADD_EXISTING_PRODUCT_TO_TRANSACTION"
export const REMOVE_PRODUCT_FROM_TRANSACTION = "REMOVE_PRODUCT_FROM_TRNSACTION"

export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"

export const RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST"

export const TRANSACTIONS_REQUEST = "TRANSACTIONS_REQUEST"
export const FETCH_ALL_TRANSACTIONS_SUCCESS = "FETCH_ALL_TRANSACTIONS_SUCCESS"
export const FETCH_ALL_TRANSACTIONS_FAILURE = "FETCH_ALL_TRANSACTIONS_FAILURE"

export const CHANGE_TRANSACTION_PAGE = "CHANGE_TRANSACTION_PAGE"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"

export const CHANGE_STATUS_FILTER = "CHANGE_STATUS_FILTER"
export const CHANGE_START_DATE_FILTER = "CHANGE_START_DATE_FILTER"
export const CHANGE_END_DATE_FILTER = "CHANGE_END_DATE_FILTER"
export const RESET_TRANSACTION_FILTERS = "RESET_TRANSACTION_FILTERS"

export const UPDATE_TRANSACTION_STATUS = "CHANGE_TRANSACTION_STATUS"