export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_FAILURE = "AUTH_FAILURE"

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'

export const RESET_PASSWORD = 'RESET_PASSWORD'

export const SESSION_EXPIRED = 'SESSION_EXPIRED'