export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAILURE = "GET_ALL_EMPLOYEE_FAILURE";

export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const CHANGE_TEAM_PAGE = "CHANGE_PAGE"