export const INVENTORY_REQUEST = "INVENTORY_REQUEST"
export const INVENTORY_SUCCESS = "INVENTORY_SUCCESS"
export const INVENTORY_FAILURE = "INVENTORY_FAILURE"

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST"
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS"
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE"

export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE"

export const CHANGE_PAGE = "CHANGE_PAGE";

export const EDIT_PRODUCT_OPEN = "EDIT_PRODUCT_OPEN"
export const EDIT_PRODUCT_CLOSE = "EDIT_PRODUCT_CLOSE"

export const UPLOAD_PRODUCTS = "UPLOAD_PRODUCTS"

export const GET_STOCK_SUMMARY_SUCCESS = "GET_STOCK_SUMMARY_SUCCESS"
export const GET_STOCK_SUMMARY_FAILURE = "GET_STOCK_SUMMARY_FAILURE"

export const CHANGE_STOCK_FILTER = "CHANGE_STOCK_FILTER"

export const SEARCH_BY_PRODUCT_ID = "SEARCH_BY_PRODUCT_ID"
export const SEARCH_BY_PRODUCT_NAME = "SEARCH_BY_PRODUCT_NAME"

export const RESET_INVENTORY_FILTERS = "RESET_INVENTORY_FILTERS"